name: VoidGen
version: '${version}'
main: de.xtkq.voidgen.VoidGen
api-version: 1.21
load: STARTUP
loadbefore: [ Multiverse-Core ]
authors: [ xtkq, PadowYT2, dxnnv ]
website: https://github.com/dxnnv/VoidGen